### ISSUE TITLE
KS comments

### ISSUE THREAD

**Issue by KewalinSamart** [jakekrol/cv-resume#5]
@jakekrol some comments and suggestions from me 
- [x] I think moving your current position (now described as Professional Experience) to after education would help the audience get some ideas what you have been up to easily. Education --> Employment History + Add full names of the PIs in each lab you have been employed in. 
- [x] 4-5 bullet points for each position should suffice to highlight your roles, responsibilities, leadership etc. It's kind of tricky as you have been part of multiple projects. I think it's okay to mention briefly about your projects but in just one to two sentence like when we tell someone when introducing ourself in a seminar. Some of the points there could probably be moved to your research project section (currently your project summaries). I think it would give you more room to elaborate on the skill sets you developed and gained. 
       - something like:
          **Research project**
          project 1
          - bullet point 1
          - bullet point 2
          project 2 etc.
- [x] As I mentioned before when we talked, I think it's good to have oral presentations and posters in two separate sections with oral presentation first
P.S. I would let you know if I come up with something more.

**Comment by jakekrol** [comment]
Thanks for the feedback, I'll try to address all these points:
- Moving `Professional Experience` section to follow after `Education`
  - Yes, I agree. Unfortunately, a combination of the `vitae` package formatting and the length of this section leads to a very bad forced page break that I do not know how to fix.
  - This will be easier to address by switching to latex/word-doc as we discussed.

- Reducing `Professional Experience` to 4-5 points and leaving details for `Research Projects` section
  - I like this idea. I will make these changes.

- Separating presentations and posters
  - Again, yes. Good point I'll do this.
